"""3rd migration

Revision ID: c699d122c587
Revises: 8204c594dea3
Create Date: 2018-09-17 10:19:43.864971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c699d122c587'
down_revision = '8204c594dea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'title')
    # ### end Alembic commands ###
